import { Project, Report, Issue } from "@/lib/store";
import { format } from "date-fns";

export default function ReportPreview({ report, issues }: { report: Report, issues: Issue[] }) {
  // We need to fetch project details from store based on ID, but store hooks 
  // can't be used conditionally inside map usually, but here we are inside a component.
  // Ideally, we pass the project as a prop. For now, let's assume we want a clean print view.
  
  return (
    <div className="font-sans text-sm text-slate-900 leading-normal">
      {/* Report Header */}
      <div className="border-b-2 border-slate-900 pb-6 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-4xl font-bold font-heading text-slate-900 mb-2">{report.title}</h1>
          <p className="text-slate-500">Report ID: #{report.id.toUpperCase()}</p>
        </div>
        <div className="text-right">
          <div className="text-2xl font-bold text-indigo-600">ReportGen</div>
          <div className="text-slate-500 text-xs mt-1">Inspection Services Ltd.</div>
        </div>
      </div>

      {/* Meta Data Grid */}
      <div className="grid grid-cols-3 gap-8 mb-10 bg-slate-50 p-6 rounded-lg border border-slate-100">
        <div>
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Date</h3>
          <p className="font-medium text-lg">{report.date}</p>
        </div>
        <div>
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Author</h3>
          <p className="font-medium text-lg">{report.author}</p>
        </div>
        <div>
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Status</h3>
          <span className="inline-block px-2 py-0.5 rounded text-sm font-bold bg-slate-200 text-slate-700">
            {report.status}
          </span>
        </div>
      </div>

      {/* Issues Table */}
      <div className="mb-8">
        <h2 className="text-xl font-bold font-heading mb-4 border-b pb-2">Inspection Findings</h2>
        
        <div className="space-y-8">
          {issues.map((issue, index) => (
            <div key={issue.id} className="break-inside-avoid border border-slate-200 rounded-lg overflow-hidden">
              <div className="bg-slate-50 p-3 border-b border-slate-200 flex justify-between items-center">
                <div className="flex items-center gap-3">
                  <span className="bg-slate-900 text-white w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold">
                    {index + 1}
                  </span>
                  <h3 className="font-bold text-lg">{issue.title}</h3>
                </div>
                <div className="flex gap-3 text-xs font-medium">
                  <span className="px-2 py-1 bg-white border rounded text-slate-600">
                    {issue.location}
                  </span>
                  <span className={`px-2 py-1 rounded border uppercase ${
                    issue.severity === "Critical" ? "bg-red-50 text-red-700 border-red-200" :
                    issue.severity === "High" ? "bg-orange-50 text-orange-700 border-orange-200" :
                    issue.severity === "Medium" ? "bg-amber-50 text-amber-700 border-amber-200" :
                    "bg-slate-100 text-slate-700 border-slate-200"
                  }`}>
                    {issue.severity}
                  </span>
                </div>
              </div>
              
              <div className="p-4 flex gap-6">
                <div className="flex-1">
                  <h4 className="text-xs font-bold text-slate-400 uppercase mb-1">Description</h4>
                  <p className="text-slate-700 mb-4">{issue.description}</p>
                  
                  <div className="flex gap-4 border-t pt-3 mt-4">
                    <div>
                      <span className="text-xs text-slate-400">Status: </span>
                      <span className="text-sm font-medium">{issue.status}</span>
                    </div>
                  </div>
                </div>
                
                {issue.photoUrl && (
                  <div className="w-48 h-32 bg-slate-100 shrink-0 border rounded-md overflow-hidden">
                     <img src={issue.photoUrl} className="w-full h-full object-cover" alt="Evidence" />
                  </div>
                )}
              </div>
            </div>
          ))}

          {issues.length === 0 && (
            <p className="text-slate-400 italic text-center py-8">No issues recorded in this report.</p>
          )}
        </div>
      </div>

      {/* Footer */}
      <div className="mt-16 pt-8 border-t border-slate-200 text-center text-slate-400 text-xs">
        <p>Generated by ReportGen on {format(new Date(), "PPP")}</p>
      </div>
    </div>
  );
}
